# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.

CONFIG_SUPPORTS_PQC ?= y
CONFIG_SUPPORTS_CURVE ?= y
WIREGUARD_MODULE_NAME ?= wireguard
WIREGUARD_FRAME_LIMIT ?= 2048

ccflags-y := -O3
ccflags-$(CONFIG_WIREGUARD_DEBUG) += -DDEBUG -g
ccflags-$(CONFIG_SUPPORTS_PQC) += -DSUPPORTS_PQC
ccflags-$(CONFIG_SUPPORTS_CURVE) += -DSUPPORTS_CURVE
ccflags-y += -D'pr_fmt(fmt)=KBUILD_MODNAME ": " fmt'
ccflags-y += -Wframe-larger-than=$(WIREGUARD_FRAME_LIMIT)
ccflags-$(if $(WIREGUARD_VERSION),y,) += -D'WIREGUARD_VERSION="$(WIREGUARD_VERSION)"'
ccflags-$(if $(WIREGUARD_GENL_NAME),y,) += -D'WIREGUARD_GENL_NAME="$(WIREGUARD_GENL_NAME)"

wireguard-y := main.o noise.o device.o peer.o timers.o queueing.o send.o receive.o socket.o peerlookup.o allowedips.o ratelimiter.o cookie.o netlink.o

include $(src)/crypto/Kbuild.include
include $(src)/compat/Kbuild.include

obj-$(if $(KBUILD_EXTMOD),m,$(CONFIG_WIREGUARD)) := wireguard.o
